<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sendIcon</name>
   <tag></tag>
   <elementGuidId>b3272588-b196-4e51-8798-3144704163d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/div/div/div[2]/div[2]/div[1]/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/div/div/div[2]/div[2]/div[1]/div[2]/button</value>
      <webElementGuid>b1493853-2d2b-452f-90ff-84d8a55165fc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
